import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import NavbarWrapper from "@/components/shared/NavbarWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const aspekta = localFont({
  src: "../public/fonts/aspekta-font-family/Aspekta-500.otf",
  variable: "--font-aspekta",
  display: "swap",
});

export const metadata: Metadata = {
  title: "ShipSafer | Production Ready Shipping Software",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className={`min-h-full flex flex-col ${aspekta.className}`}>
        <NavbarWrapper/>
        {children}</body>
    </html>
  );
}
